### ISSUE TITLE
Close PRs opened in sandbox, and notify requestor of this action

### ISSUE THREAD

**Issue by clyne** [ProjectPythia/github-sandbox#11]
A small number of PRs, such as #10, have been opened in the Sandbox repo. Rather than simply leaving them open indefinitely we should

1. Add a bot to auto-comment on new PRs in the sandbox, informing the creator that the PR will be closed in future without being merged
2. Add a bot to auto-close stale PRs in the sandbox

**Comment by brian-rose** [comment]
This was taken care of in #13. Closing this issue now.
